FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:buster

# Default page to load
ENV BROWSER_URL="http://192.168.50.10" \
    DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN apt-get update && apt-get install -y \
    chromium-browser \
    matchbox-window-manager \
    xinit \
    x11-xserver-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY start.sh /usr/src/start.sh
RUN chmod +x /usr/src/start.sh

CMD ["/usr/src/start.sh"]
